routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/{any}', function(){
// 	return view('home');
// })->where('any', '.*');

Route::get('/', ['as' => 'login', 'uses' => 'HomeController@showLogin']);

Route::post('/', ['as' => 'login', 'uses' => 'HomeController@doLogin']);

Route::get('logout', ['uses' => 'HomeController@doLogout']);

Route::get('dashboard', function() {
		return view('dashboard')->with([
			'organizations'		=>	App\Organization::where('id', '<=', 5)->get(),
			'total_employees'	=>	App\Employee::where('emp_no', 'NOT LIKE', '%SysAd%')->count(),
			'total_users'		=>	App\User::count(),
			'dosri'				=>	App\Relations::leftJoin('employees', 'relations.emp_id', '=', 'employees.id')->whereIn('employees.job_level', [1,2,3,4,5,6])->count(),
			'era'				=>	App\Relations::leftJoin('employees', 'relations.emp_id', '=', 'employees.id')->where('job_level', '=', 7)->count(),
		]);
})->middleware('auth');

Route::post('dashboard', 'QuickEmailController@send')->middleware('auth');

Route::get('genderdata', 'ReportController@genderChart');
Route::get('empstatusdata', 'ReportController@empStatusChart');

Route::get('profile', function() {
	return view('profile')->with([
		'emp_details'		=>	App\Employee::where('id', auth()->user()->emp_id)->get(),
		'contacts'      	=>  App\Contacts::where('emp_id', '=', auth()->user()->emp_id)->orderBy('category')->get(),
		'relations'			=>	App\Relations::where('emp_id', '=', auth()->user()->emp_id)->orderBy('consanguinity')->get(),
		'personal_ids'		=>	DB::table('personal_ids')->select('personal_ids.*', 'id_type.desc AS id_type')
								->leftJoin('id_type', 'id_type.id', '=', 'personal_ids.type')
								->where('emp_id', auth()->user()->emp_id)
								->get(),
		'educ_attainment'	=>	DB::table('educational_attainment')->select('educational_attainment.*', 'education_level.desc AS educ_level')
								->leftJoin('education_level', 'education_level.id', '=', 'educational_attainment.level')
								->where('emp_id', auth()->user()->emp_id)
								->orderBy('educational_attainment.year_start')
								->get(),
		'emp_history'		=>	DB::table('employment_history')->select('employment_history.*')
								->where('emp_id', auth()->user()->emp_id)
								->orderBy('employment_history.date_start')
								->get(),
	]);
})->middleware('auth');

// Downloads
Route::get('era-form-download', ['as' => 'eraform.download', 'uses' => function() {
		return Response::download('downloads/ERA-Fillup-Form.xlsx', 'era-fillup-form.xlsx');
	}])->middleware('auth');
Route::get('rpt-form-download', ['as' => 'rptform.download', 'uses' => function() {
		return Response::download('downloads/RPT-Fillup-Form.xlsx', 'rpt-fillup-form.xlsx');
	}])->middleware('auth');
Route::get('it-request-form-download', ['as' => 'itrequestform.download', 'uses' => function() {
		return Response::download('downloads/IT-REQUEST-FORM.pdf', 'it-request-form.pdf');
	}])->middleware('auth');
Route::get('user-request-form-download', ['as' => 'userrequestform.download', 'uses' => function() {
		return Response::download('downloads/USER-REQUEST-FORM.pdf', 'user-request-form.pdf');
	}])->middleware('auth');

Route::resource('user', 'UserController');
Route::prefix('user')->group(function(){
	Route::put('/resetpassword/{id}', 'UserController@resetPassword');
	Route::put('/updatepassword/{id}', 'UserController@updatePassword');
});


Route::resource('employee', 'EmployeeController');
Route::prefix('employee')->group(function(){
	Route::post('/photo', 'EmpPhotoController@empImage');
	Route::delete('/removeContact/{id}', 'EmployeeController@removeContact');
	Route::delete('/relation/{id}', 'RelationController@destroy');
	Route::get('/locations/{id}', 'EmployeeController@orgLocationList');
	Route::get('/jobs/{id}', 'EmployeeController@catJobList');
	Route::resource('/relation', 'RelationController');
	Route::resource('/salary', 'EmpBasicSalaryController');
});

Route::get('amla', function(Request $request){
	return view('amla')->with([
		'page_title'	=>	'AMLA Watchlist',
		'api'			=>	'/api/amla/',
		'crime_types'	=>	App\CrimeType::select('crime_type.id', 'crime_type.desc AS text')->pluck('text', 'id'),
		'amla_types'	=>	App\AMLAType::pluck('desc', 'id'),
		'user_id'		=>	$request->user()->id,
		'user'			=>	$request->user(),
	]);
})->middleware('auth');

Route::get('amlagroup', function(Request $request){
	return view('amlagroup')->with([
		'page_title'		=>	'AMLA Group Watchlist',
		'api_countries'		=>	'/api/amlagroup/countries/type',
		'api_corporation'	=>	'/api/amlagroup/corporation/type',
		'user_id'			=>	$request->user()->id,
		'user'				=>	$request->user(),
	]);
})->middleware('auth');

Route::prefix('reports')->middleware('auth')->group(function(){
	Route::get('/employee-master', function(){
		return view('report_emp')->with([
			'report_title'		=>	'Employee Master List Report (All)',
			'companies'     	=>  App\Organization::whereBetween('organization.id', [1,5])->pluck('desc', 'id')
		]);
	});
	Route::get('/employee-master/{id}', function(Request $request){
		return view('report_emp')->with([
			'report_title'		=>	'Employee Master List Report (All)',
			'companies'     	=>  App\Organization::whereBetween('organization.id', [1,5])->pluck('desc', 'id'),
			'request'			=>	$request
		]);
	});
	Route::get('/employee/{id}', [
				'as'	=> 'reports.employee', 
				'uses'	=> 'ReportController@showEmpRelatives']);
	Route::get('/employee-related-accounts', function(){
		return view('report_era')->with(['report_title'=>'Employee Related Accounts Report (All)']);
	});
	Route::get('/employee-related-accounts/{group}', function(Request $request){
		return view('report_era')->with([
			'report_title'	=>	'Employee Related Accounts Report (All)',
			'request'		=>	$request
			]);
	});
	Route::get('/customer-uploads', function(Request $request){
		return view('report_customer_uploads')->with([
			'request'		=>	$request,
		]);
	});
	// Route::get('/attachments/{category}', function(Request $request){
	// 	return view('report_customer_uploads')->with([
	// 		'request'		=>	$request,
	// 	]);
	// });
	Route::get('/resigned', function(Request $request){
		return view('report_emp_resigned')->with([
			'report_title'	=>	'MRB - List of Resigned Employees',
			'request'		=>	$request
			]);
	});
	// API call
	Route::get('/emp-master/{id}', 'ReportController@employeesAPI');
	Route::get('/emp-master/resigned/{date_from}/{date_to}', 'ReportController@getResignedEmployees');
	Route::get('/emp-related-all', 'ReportController@employeeRelatedAllAPI');
	Route::get('/emp-related-dosri', 'ReportController@employeeRelatedDosriAPI');
	Route::get('/emp-related-accounts', 'ReportController@employeeRelatedAccountsAPI');
});

Route::prefix('job')->middleware('auth')->group(function(){
	Route::resource('/title', 'JobTitleController');
	Route::resource('/category', 'JobCategoryController');
	Route::resource('/level', 'JobLevelController');
	Route::resource('/status', 'EmpStatusController');
	Route::resource('/paygrade', 'PayGradeController');
});

Route::prefix('setup')->middleware('auth')->group(function(){
	//Route::resource('/skills', 'OrganizationController');
	//Route::resource('/education', 'OrganizationController');
	Route::resource('/organization', 'OrganizationController');
	Route::resource('/location', 'LocationController');
});

Route::prefix('setups')->middleware('auth')->group(function(){
	Route::get('/attachmentcategory', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/attachmenttype', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/amlatype', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/region', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	// Route::get('/postalcode', function(Request $request){
	// 	return view('setup_main')->with(['request' => $request]);
	// });
	Route::get('/crimetype', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/infosource', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/infosourcetype', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/idtype', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
	Route::get('/educlevel', function(Request $request){
		return view('setup_main')->with(['request' => $request]);
	});
});

Route::get('test', function(){
	$notifications = Auth::user()->unreadNotifications;
	foreach ($notifications as $notification) {
		dd($notification->data['reset']);
		$notification->markAsRead();
	}
});

Route::get('/markAsRead', function(){
	Auth::user()->unreadNotifications->markAsRead();
})->middleware('auth');


Route::get('json/{id}', [
		'as' 	=>	'json',
		'uses'	=>	'UserController@getRoles'
	]);

Route::get('auth', function (Request $request) {
        return $request->user()->id;
});	

// ICBS Connection
Route::get('icbs', function(){
	return response()->json([
		'data'	=>	App\Customer::select('customer_id', 'display_name')->limit(100)->get()
	]);
});

Route::get('customers', function(Request $request){
	return view('customers')->with([
		'page_title'	=>	'Customer List',
		'api'			=>	'/api/customer/',
		'user_id'		=>	$request->user()->id,
		'user'			=>	$request->user(),
	]);
})->middleware('auth');

Route::get('/customers/{id}', function(Request $request, $id){
	return view('customers-profile')->with([

resources/views/error.blade.php
@extends('layouts.master')

@section('title', 'Error Page')

@section('breadcrumb_title', 'Error Page')

@section('content')
<div class="row">
	<div class="col-xs-12">
		@if($error)
		<div class="text-center">
			<h1 class="errormsg">{{ $error }}</h1>
			<p class="errormsg">{{ $message }}</p>
		</div>
		@endif	
	</div>
</div>
@endsection

resources/views/job_cat_list.blade.php
@extends('layouts.master')

@section('css_styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  
@endsection

@section('title', 'Job Categories')

@section('page_title', 'Job Categories')

@section('breadcrumb_title', 'Job Categories')

@section('content')

@if ($flash = session('message'))
  <div id="toast-container" class="flash-message toast-bottom-right">
    <div class="toast toast-success" aria-live="polite" style="display: block;">
      <div class="toast-message">{{ $flash }}</div>
    </div>  
  </div>
@endif

<div class="row">
<div class="col-xs-12">
  <div class="box box-success">
    <div class="box-header">
      <a href="{{ route('category.create') }}" class="btn btn-success">Create Job Category</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
    @if (count($job_categories) > 0)  
        <table id="mbTbl1" class="table table-bordered table-hover dt-responsive">
          <thead>
            <tr>
              <th>ID</th>
              <th>Job Category</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($job_categories as $job_category)  
            <tr>
              <td><a class="text-success" href="{{ route('category.edit', ['id' => $job_category->id]) }}">{{ $job_category->id }}</a></td>
              <td><a class="text-success" href="{{ route('category.edit', ['id' => $job_category->id]) }}">{{ $job_category->desc }}</a></td>
            </tr>
          @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>Job Category</th>
            </tr>
          </tfoot>
        </table>  <!-- / table -->  
    @endif      
    </div>  <!-- / .box-body -->  
  </div> <!-- / .box -->  
</div>  <!-- / .col -->
</div>  <!-- / .row -->
@endsection

@section('scripts')
<!-- DataTables -->
<script src="{{ asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#mbTbl1').DataTable()
    $('#mbTbl2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/job_list.blade.php
@extends('layouts.master')

@section('css_styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  
@endsection

@section('title', 'Job Titles')

@section('page_title', 'Job Titles')

@section('breadcrumb_title', 'Job Titles')

@section('content')

@if ($flash = session('message'))
  <div id="toast-container" class="flash-message toast-bottom-right">
    <div class="toast toast-success" aria-live="polite" style="display: block;">
      <div class="toast-message">{{ $flash }}</div>
    </div>  
  </div>
@endif

<div class="row">
<div class="col-xs-12">
  <div class="box box-success">
    <div class="box-header">
      <a href="{{ route('title.create') }}" class="btn btn-success">Create Job Title</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
    @if (count($job_titles) > 0)  
        <table id="mbTbl1" class="table table-bordered table-hover dt-responsive">
          <thead>
            <tr>
              <th>ID</th>
              <th>Job Title</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($job_titles as $job_title)  
            <tr>
              <td><a class="text-success" href="{{ route('title.edit', ['id' => $job_title->id]) }}">{{ $job_title->id }}</a></td>
              <td><a class="text-success" href="{{ route('title.edit', ['id' => $job_title->id]) }}">{{ $job_title->desc }}</a></td>
            </tr>
          @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>Job Title</th>
            </tr>
          </tfoot>
        </table>  <!-- / table -->  
    @endif      
    </div>  <!-- / .box-body -->  
  </div> <!-- / .box -->  
</div>  <!-- / .col -->
</div>  <!-- / .row -->
@endsection

@section('scripts')
<!-- DataTables -->
<script src="{{ asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#mbTbl1').DataTable()
    $('#mbTbl2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/job_status_list.blade.php
@extends('layouts.master')

@section('css_styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  
@endsection

@section('title', 'Job Employment Status')

@section('page_title', 'Job Employment Status')

@section('breadcrumb_title', 'Job Employment Status')

@section('content')

@if ($flash = session('message'))
  <div id="toast-container" class="flash-message toast-bottom-right">
    <div class="toast toast-success" aria-live="polite" style="display: block;">
      <div class="toast-message">{{ $flash }}</div>
    </div>  
  </div>
@endif

<div class="row">
<div class="col-xs-12">
  <div class="box box-success">
    <div class="box-header">
      <a href="{{ route('status.create') }}" class="btn btn-success">Create Employment Status</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
    @if (count($emp_statuses) > 0)  
        <table id="mbTbl1" class="table table-bordered table-hover dt-responsive">
          <thead>
            <tr>
              <th>ID</th>
              <th>Employment Status</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($emp_statuses as $emp_status)  
            <tr>
              <td><a class="text-success" href="{{ route('status.edit', ['id' => $emp_status->id]) }}">{{ $emp_status->id }}</a></td>
              <td><a class="text-success" href="{{ route('status.edit', ['id' => $emp_status->id]) }}">{{ $emp_status->desc }}</a></td>
            </tr>
          @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>Employment Status</th>
            </tr>
          </tfoot>
        </table>  <!-- / table -->  
    @endif      
    </div>  <!-- / .box-body -->  
  </div> <!-- / .box -->  
</div>  <!-- / .col -->
</div>  <!-- / .row -->
@endsection

@section('scripts')
<!-- DataTables -->
<script src="{{ asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#mbTbl1').DataTable()
    $('#mbTbl2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/pay_grades_list.blade.php
@extends('layouts.master')

@section('css_styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  
@endsection

@section('title', 'Pay Grades')

@section('page_title', 'Pay Grades')

@section('breadcrumb_title', 'Pay Grades')

@section('content')

@if ($flash = session('message'))
  <div id="toast-container" class="flash-message toast-bottom-right">
    <div class="toast toast-success" aria-live="polite" style="display: block;">
      <div class="toast-message">{{ $flash }}</div>
    </div>  
  </div>
@endif

<div class="row">
<div class="col-xs-12">
  <div class="box box-success">
    <div class="box-header">
      <a href="{{ route('paygrade.create') }}" class="btn btn-success">Create Pay Grade</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
    @if (count($pay_grades) > 0)  
        <table id="mbTbl1" class="table table-bordered table-hover dt-responsive">
          <thead>
            <tr>
              <th>ID</th>
              <th>Pay Grade</th>
              <th>Mininum Salary</th>
              <th>Maximum Salary</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($pay_grades as $pay_grade)  
            <tr>
              <td><a class="text-success" href="{{ route('paygrade.edit', ['id' => $pay_grade->id]) }}">{{ $pay_grade->id }}</a></td>
              <td><a class="text-success" href="{{ route('paygrade.edit', ['id' => $pay_grade->id]) }}">{{ $pay_grade->desc }}</a></td>
              <td>{{ number_format($pay_grade->min_salary, 2) }}</td>
              <td>{{ number_format($pay_grade->max_salary, 2) }}</td>
            </tr>
          @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>Pay Grade</th>
              <th>Mininum Salary</th>
              <th>Maximum Salary</th>
            </tr>
          </tfoot>
        </table>  <!-- / table -->  
    @endif      
    </div>  <!-- / .box-body -->  
  </div> <!-- / .box -->  
</div>  <!-- / .col -->
</div>  <!-- / .row -->
@endsection

@section('scripts')
<!-- DataTables -->
<script src="{{ asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#mbTbl1').DataTable()
    $('#mbTbl2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/setup_location_list.blade.php
@extends('layouts.master')

@section('css_styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  
@endsection

@section('title', 'Location')

@section('page_title', 'Location')

@section('breadcrumb_title', 'Location')

@section('content')

@if ($flash = session('message'))
  <div id="toast-container" class="flash-message toast-bottom-right">
    <div class="toast toast-success" aria-live="polite" style="display: block;">
      <div class="toast-message">{{ $flash }}</div>
    </div>  
  </div>
@endif

<div class="row">
<div class="col-xs-12">
  <div class="box box-success">
    <div class="box-header">
      <a href="{{ route('location.create') }}" class="btn btn-success">Create Location</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
    @if (count($locations) > 0)  
        <table id="mbTbl1" class="table table-bordered table-hover dt-responsive">
          <thead>
            <tr>
              <th>ID</th>
              <th>Organization</th>
              <th>Location Name</th>
              <th>Address</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($locations as $location)  
            <tr>
              <td><a class="text-success" href="{{ route('location.edit', ['id' => $location->id]) }}">{{ $location->id }}</a></td>
              <td>{{ $location->getOrg->desc }}</td>
              <td><a class="text-success" href="{{ route('location.edit', ['id' => $location->id]) }}">{{ $location->desc }}</a></td>
              <td>{{ $location->address }}</td>
              <td>
                <a href="#" class="delete-modal btn btn-danger" data-toggle="tooltip" title="Delete" data-id="{{ $location->id }}" data-desc="{{ $location->desc }}"><i class="fa fa-trash"></i></a>
                <a href="{{ route('location.edit', ['id' => $location->id]) }}" class="btn btn-warning" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a>
              </td>
            </tr>
          @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>Organization</th>
              <th>Location Name</th>
              <th>Address</th>
              <th>Actions</th>
            </tr>
          </tfoot>
        </table>  <!-- / table -->  
    @endif      
    </div>  <!-- / .box-body -->  
  </div> <!-- / .box -->  
</div>  <!-- / .col -->
</div>  <!-- / .row -->
@endsection

@section('scripts')
<!-- DataTables -->
<script src="{{ asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#mbTbl1').DataTable()
    $('#mbTbl2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/user_list.blade.php
@extends('layouts.master')

@section('css_styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  
@endsection

@section('title', 'User List')

@section('page_title', 'User List')

@section('breadcrumb_title', 'User List')

@section('content')

@if ($flash = session('message'))
  <div id="toast-container" class="flash-message toast-bottom-right">
    <div class="toast toast-success" aria-live="polite" style="display: block;">
      <div class="toast-message">{{ $flash }}</div>
    </div>  
  </div>
@endif

<div class="row">
<div class="col-xs-12">
  <div class="box box-success">
    <div class="box-header">
      <a href="{{ route('user.create') }}" class="btn btn-success">Create User</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
    @if (count($users) > 0)  
        <table id="userTbl1" class="table table-bordered table-hover dt-responsive">
          <thead>
            <tr>
              <th>Logged In</th>
              <th>Employee Name</th>
              <th>Username</th>
              <th>Branch</th>
              <!-- <th>Roles</th> -->
              <th>Status</th>
              <th style="width: 14%;">Actions</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($users as $user)  
            <tr class="item{{ $user->id }}">
              <td>
              @if($user->isOnline())
                <i class="fa fa-circle text-success"></i> Online  
              @else
                <i class="fa fa-circle text-danger"></i> Offline  
              @endif
              </td>
              <td><a class="text-success" href="#">{{ $user->employee->lastname }}, {{ $user->employee->firstname }} {{ $user->employee->middlename }}</a></td>
              <td>{{ $user->username }}</td>
              <td>{{ $user->employee->getLocation->desc }}</td>
              <!--<td>
              @foreach($user->roles as $role)
                <span class="badge bg-green">{{ $role->name }}</span>
              @endforeach  
              </td> -->
              <td><span class="badge {{ $user->deleted == 0 ? 'bg-green' : 'bg-red' }}">{{ $user->deleted == 0 ? 'Active' : 'Inactive' }}</span></td>
              <td>
                  <a href="#" data-toggle="tooltip" title="Reset Password" class="reset-password btn btn-primary" data-reset-id="{{ $user->id }}" data-reset-username="{{ $user->username }}"><i class="fa fa-key"></i></a>
                  <a href="#" data-toggle="tooltip" title="Edit" class="edit-user btn btn-warning" data-id="{{ $user->id }}" data-emp-id="{{ $user->emp_id }}" data-username="{{ $user->username }}" data-status="{{ $user->deleted }}"><i class="fa fa-edit"></i></a>                   
                  <a href="#" data-toggle="tooltip" title="Delete" class="delete-user btn btn-danger" data-del-id="{{ $user->id }}" data-del-username="{{ $user->username }}"><i class="fa fa-trash"></i></a>
              </td>
            </tr>
          @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>Employee Name</th>
              <th>Username</th>
              <th>Roles</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </tfoot>
        </table>  <!-- / table -->  
    @endif      
    </div>  <!-- / .box-body -->  
  </div> <!-- / .box -->  
</div>  <!-- / .col -->
</div>  <!-- / .row -->

@include('partials._modal-user')
    
@endsection

@section('scripts')
<!-- DataTables -->
<script src="{{ asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('adminlte/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
<!-- passwordGenerator -->
<script src="{{ asset('custom/js/passwordGenerator.js') }}"></script>
<!-- page script -->
<script src="{{ asset('custom/js/userValidation.js') }}"></script>
@endsection